// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6uYy0PgpREnUc2P0MAzwnukIfgSH8UE8',
    appId: '1:755505103647:web:895ff11a021b40e8dfe62a',
    messagingSenderId: '755505103647',
    projectId: 'smart-learn-mtbc',
    authDomain: 'smart-learn-mtbc.firebaseapp.com',
    storageBucket: 'smart-learn-mtbc.firebasestorage.app',
    measurementId: 'G-FZG0KYPRL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6_ZhaDFR1BdwPZG4ldteTzH9TymOABjY',
    appId: '1:755505103647:android:c38724190e68fdfcdfe62a',
    messagingSenderId: '755505103647',
    projectId: 'smart-learn-mtbc',
    storageBucket: 'smart-learn-mtbc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNbHvdQGZ5YfgGSZquUfbg7ldZKS6MkPU',
    appId: '1:755505103647:ios:5340e17149a1a28bdfe62a',
    messagingSenderId: '755505103647',
    projectId: 'smart-learn-mtbc',
    storageBucket: 'smart-learn-mtbc.firebasestorage.app',
    iosBundleId: 'com.asteriq.smartLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNbHvdQGZ5YfgGSZquUfbg7ldZKS6MkPU',
    appId: '1:755505103647:ios:5340e17149a1a28bdfe62a',
    messagingSenderId: '755505103647',
    projectId: 'smart-learn-mtbc',
    storageBucket: 'smart-learn-mtbc.firebasestorage.app',
    iosBundleId: 'com.asteriq.smartLearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6uYy0PgpREnUc2P0MAzwnukIfgSH8UE8',
    appId: '1:755505103647:web:00dde65ec7a327f2dfe62a',
    messagingSenderId: '755505103647',
    projectId: 'smart-learn-mtbc',
    authDomain: 'smart-learn-mtbc.firebaseapp.com',
    storageBucket: 'smart-learn-mtbc.firebasestorage.app',
    measurementId: 'G-GNLDC2N9JW',
  );
}
